[build-system]
requires = [
    "setuptools",
    "wheel",
    "pycryptodome", # <-- required because the module is imported in setup.py
    "loolclitools"  # <--
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
